# Dynamic config
http:
  routers:
    rootDomain:
      rule: "Host(`localhost`)"
      entryPoints:
        - https
      service: "api@internal"
  middlewares:
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true
    crowdsec-bouncer-traefik-plugin:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: "${CROWDSEC_LAPI_KEY}"
          Enabled: "true"
